spring:
  redis:
    database: 0
#    host: 127.0.0.1
#    port: 6379
    cluster:
      nodes: 39.100.24.206:7000,39.100.24.206:7001,39.100.24.206:7002,39.99.183.143:7000,39.99.183.143:7001,39.99.183.143:7002
      max-redirects: 3  # 重定向重试次数
    jedis:
      pool:
        max-active: 20  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 3000  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10    # 连接池中的最大空闲连接
        min-idle: 0     # 连接池中的最小空闲连接
    timeout: 10000
    password: adminLX
